name: w_flux_example
version: 2.10.24
description: Flux library for uni-directional dataflow inspired by reflux and Facebook's
    flux architecture.
homepage: https://github.com/Workiva/w_flux
publish_to: none
environment:
    sdk: '>=2.19.0 <3.0.0'
dependencies:
  w_flux:

dev_dependencies:
  react: ^7.0.0
  build_runner: ^2.0.0
  build_web_compilers: '>=3.0.0 <5.0.0'
  dart_dev: ^4.0.0
  dart_style: ^2.1.1
  dependency_validator: ^3.0.0

dependency_overrides:
  w_flux:
    path: ../
  react:
    git:
      url: git@github.com:Workiva/react-dart.git
      ref: react-18-2-0-testing
  react_testing_library:
    git:
      url: git@github.com:Workiva/react_testing_library.git
      ref: r18
  dart_dev_workiva:
    git:
      url: git@github.com:Workiva/dart_dev_workiva.git
      ref: override-react-js-files-for-r18
