name: w_flux
version: 3.0.1
description: Flux library for uni-directional dataflow inspired by reflux and Facebook's
    flux architecture.
homepage: https://github.com/Workiva/w_flux

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  meta: ^1.16.0
  react: ^7.0.0
  w_common: ^3.0.0

dev_dependencies:
  build_runner: ^2.0.0
  build_test: ^2.1.3
  build_web_compilers: '>=3.0.0 <5.0.0'
  dart_dev: ^4.0.0
  dependency_validator: ^3.0.0
  test: ^1.18.2
  workiva_analysis_options: ^1.4.1

dependency_overrides:
  react:
    git:
      url: git@github.com:Workiva/react-dart.git
      ref: react-18-2-0-testing
  react_testing_library:
    git:
      url: git@github.com:Workiva/react_testing_library.git
      ref: r18
  dart_dev_workiva:
    git:
      url: git@github.com:Workiva/dart_dev_workiva.git
      ref: override-react-js-files-for-r18
